<?php

namespace MikroApi\Tests\Postgres;

use MikroApi\Attributes\Schema\Column;
use MikroApi\Attributes\Schema\ForeignKey;
use MikroApi\Attributes\Schema\Index;
use MikroApi\Attributes\Schema\PrimaryKey;
use MikroApi\Attributes\Schema\SoftDeletes;
use MikroApi\Attributes\Schema\Table;
use MikroApi\Attributes\Schema\Timestamps;
use MikroApi\Attributes\Schema\Unique;
use MikroApi\Database\Database;
use MikroApi\Database\Migration;
use MikroApi\Database\SchemaBuilder;
use MikroApi\Repository\BaseRepository;
use PHPUnit\Framework\TestCase;

/**
 * Tests del dialecto PostgreSQL. Los de generación de SQL corren siempre;
 * los de integración solo si hay un servidor disponible:
 *
 *   docker run --rm -d -p 5432:5432 -e POSTGRES_PASSWORD=secret postgres:16
 *   MIKRO_PG_HOST=127.0.0.1 MIKRO_PG_PASSWORD=secret vendor/bin/phpunit tests/PostgresTest.php
 */
class PostgresTest extends TestCase
{
    /* ------------------------------------------------------------------ */
    /*  Traducción de dialecto                                              */
    /* ------------------------------------------------------------------ */

    public function testDriverAliasesNormalizeToPgsql(): void
    {
        $this->assertSame('pgsql', Database::normalizeDriver('postgres'));
        $this->assertSame('pgsql', Database::normalizeDriver('PostgreSQL'));
        $this->assertSame('pgsql', Database::normalizeDriver('pgsql'));
        $this->assertSame('mysql', Database::normalizeDriver('mysql'));
    }

    public function testBackticksBecomeDoubleQuotesOnlyForPgsql(): void
    {
        $sql = "SELECT `users`.* FROM `users` WHERE `name` = ?";

        $this->assertSame('SELECT "users".* FROM "users" WHERE "name" = ?', Database::toDialect($sql, 'pgsql'));
        $this->assertSame($sql, Database::toDialect($sql, 'mysql'));
        $this->assertSame($sql, Database::toDialect($sql, 'sqlite'));
    }

    public function testBackticksInsideStringLiteralsAreKept(): void
    {
        $sql = "SELECT `a` FROM `t` WHERE `b` = 'it''s `raw`' AND `c` = 'x'";

        $this->assertSame(
            "SELECT \"a\" FROM \"t\" WHERE \"b\" = 'it''s `raw`' AND \"c\" = 'x'",
            Database::toDialect($sql, 'pgsql'),
        );
    }

    /* ------------------------------------------------------------------ */
    /*  SchemaBuilder                                                       */
    /* ------------------------------------------------------------------ */

    public function testCreateTableForPgsql(): void
    {
        $sql = (new SchemaBuilder('postgres'))->buildCreateTable(PgArticlesMigration::class);

        $this->assertStringContainsString('CREATE TABLE IF NOT EXISTS "articles"', $sql);
        $this->assertStringContainsString('"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', $sql);
        $this->assertStringContainsString('"title" VARCHAR(200) NOT NULL', $sql);
        $this->assertStringContainsString('"price" NUMERIC(8,2) NOT NULL DEFAULT 0', $sql);
        $this->assertStringContainsString('"published" BOOLEAN NOT NULL DEFAULT FALSE', $sql);
        $this->assertStringContainsString('"meta" JSONB NULL', $sql);
        $this->assertStringContainsString("\"status\" VARCHAR(20) NOT NULL DEFAULT 'it''s draft'", $sql);
        $this->assertStringContainsString('"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP', $sql);
        $this->assertStringContainsString('"deleted_at" TIMESTAMP NULL DEFAULT NULL', $sql);
        $this->assertStringContainsString(
            'CONSTRAINT "fk_articles_author_id" FOREIGN KEY ("author_id") REFERENCES "authors" ("id") ON DELETE CASCADE',
            $sql,
        );
        $this->assertStringContainsString('CREATE UNIQUE INDEX IF NOT EXISTS "uniq_articles_slug" ON "articles" ("slug");', $sql);
        $this->assertStringContainsString('CREATE INDEX IF NOT EXISTS "idx_articles_deleted_at" ON "articles" ("deleted_at");', $sql);
        $this->assertStringContainsString("COMMENT ON COLUMN \"articles\".\"title\" IS 'Título visible';", $sql);
        $this->assertStringContainsString("COMMENT ON TABLE \"articles\" IS 'Artículos del blog';", $sql);
        $this->assertStringNotContainsString('`', $sql);
        $this->assertStringNotContainsString('AUTO_INCREMENT', $sql);
        $this->assertStringNotContainsString('ENGINE', $sql);
    }

    public function testUuidPrimaryKeyIsNotIdentity(): void
    {
        $sql = (new SchemaBuilder('pgsql'))->buildCreateTable(PgTokensMigration::class);

        $this->assertStringContainsString('"id" UUID NOT NULL PRIMARY KEY', $sql);
    }

    public function testAlterTableForPgsqlUsesSingleStatement(): void
    {
        // PDO SQLite: la consulta a information_schema falla → se asume tabla vacía
        $pdo = new \PDO('sqlite::memory:');
        $sql = (new SchemaBuilder('pgsql'))->buildAlterTable(PgArticlesMigration::class, $pdo);

        $this->assertSame(1, \substr_count($sql, 'ALTER TABLE "articles"'));
        $this->assertStringContainsString('ADD COLUMN "title" VARCHAR(200) NULL', $sql); // NOT NULL relajado
        $this->assertStringContainsString('ADD CONSTRAINT "fk_articles_author_id"', $sql);
        $this->assertStringContainsString('CREATE UNIQUE INDEX IF NOT EXISTS "uniq_articles_slug"', $sql);
    }

    public function testDropTableForPgsql(): void
    {
        $this->assertSame(
            'DROP TABLE IF EXISTS "articles";',
            (new SchemaBuilder('pgsql'))->buildDropTable(PgArticlesMigration::class),
        );
    }

    public function testMysqlAndSqliteOutputUnchanged(): void
    {
        $mysql  = (new SchemaBuilder('mysql'))->buildCreateTable(PgArticlesMigration::class);
        $sqlite = (new SchemaBuilder('sqlite'))->buildCreateTable(PgArticlesMigration::class);

        $this->assertStringContainsString('`id` INT NOT NULL AUTO_INCREMENT', $mysql);
        $this->assertStringContainsString('`published` TINYINT(1) NOT NULL DEFAULT 0', $mysql);
        $this->assertStringContainsString('`id` INTEGER PRIMARY KEY AUTOINCREMENT', $sqlite);
    }

    /* ------------------------------------------------------------------ */
    /*  Integración (requiere servidor)                                     */
    /* ------------------------------------------------------------------ */

    private function connect(): Database
    {
        $host = \getenv('MIKRO_PG_HOST');
        if (!$host || !\extension_loaded('pdo_pgsql')) {
            $this->markTestSkipped('Define MIKRO_PG_HOST para correr la integración con PostgreSQL.');
        }

        Database::reset();
        $db = Database::connect([
            'driver'   => 'postgres',
            'host'     => $host,
            'port'     => (int) (\getenv('MIKRO_PG_PORT') ?: 5432),
            'database' => \getenv('MIKRO_PG_DATABASE') ?: 'postgres',
            'username' => \getenv('MIKRO_PG_USER') ?: 'postgres',
            'password' => \getenv('MIKRO_PG_PASSWORD') ?: '',
        ]);
        $db->execute('DROP TABLE IF EXISTS `articles`; DROP TABLE IF EXISTS `authors`;');
        return $db;
    }

    protected function tearDown(): void
    {
        Database::reset();
    }

    public function testIntegrationMigrationsAndRepository(): void
    {
        $db = $this->connect();

        foreach ([PgAuthorsMigration::class, PgArticlesMigration::class] as $class) {
            $db->execute((new $class('pgsql', $db->getPdo()))->up());
        }

        $authors  = new PgAuthorRepository($db);
        $articles = new PgArticleRepository($db);

        $author = $authors->create(['name' => 'Ana']);
        $this->assertSame(1, $author['id']);

        $article = $articles->create([
            'author_id' => $author['id'],
            'title'     => 'Hola',
            'slug'      => 'hola',
            'published' => false,
        ]);
        $this->assertFalse($article['published']);
        $this->assertSame('0.00', $article['price']);

        $updated = $articles->update($article['id'], ['published' => true]);
        $this->assertTrue($updated['published']);

        $this->assertSame(1, $articles->count());
        $this->assertSame(1, $articles->paginate(1, 10)['total']);
        $this->assertTrue($articles->delete($article['id'])); // soft delete
        $this->assertSame(0, $articles->count());
        $this->assertNotNull($articles->restore($article['id']));

        // Re-ejecutar up() con la tabla existente genera ALTER sin cambios
        $this->assertSame('-- No hay cambios que aplicar', (new PgArticlesMigration('pgsql', $db->getPdo()))->up());
    }
}

/* ======================================================================= */
/*  Fixtures                                                                */
/* ======================================================================= */

#[Table('authors')]
class PgAuthorsMigration extends Migration
{
    #[PrimaryKey]
    #[Column(type: 'int')]
    public int $id;

    #[Column(type: 'varchar', length: 100)]
    public string $name;
}

#[Table('articles', comment: 'Artículos del blog')]
#[Timestamps]
#[SoftDeletes]
class PgArticlesMigration extends Migration
{
    #[PrimaryKey]
    #[Column(type: 'int')]
    public int $id;

    #[Column(type: 'int')]
    #[ForeignKey(references: 'authors', on: 'id', onDelete: 'CASCADE')]
    public int $authorId;

    #[Column(type: 'varchar', length: 200, comment: 'Título visible')]
    public string $title;

    #[Column(type: 'varchar', length: 200)]
    #[Unique]
    public string $slug;

    #[Column(type: 'decimal', precision: 8, scale: 2, default: 0)]
    public float $price;

    #[Column(type: 'boolean', default: false)]
    public bool $published;

    #[Column(type: 'json', nullable: true)]
    public ?array $meta;

    #[Column(type: 'varchar', length: 20, default: "it's draft")]
    #[Index]
    public string $status;
}

#[Table('tokens')]
class PgTokensMigration extends Migration
{
    #[PrimaryKey(autoIncrement: false)]
    #[Column(type: 'uuid')]
    public string $id;
}

class PgAuthorRepository extends BaseRepository
{
    protected string $table         = 'authors';
    protected bool   $useTimestamps = false;
}

class PgArticleRepository extends BaseRepository
{
    protected string $table          = 'articles';
    protected bool   $useSoftDeletes = true;
}
